### PR TITLE
Fix gold reward on inspect

### LINKED ISSUE #70: Hero doesn't pick up gold from treasures
I have introduced this game at work, and a colleague and me have noticed that whenever "rpg ls" finds a treasure that contains gold the gold count of the hero doesn't increase. I attach the output from the terminal:
```fish
cmg in ❯ ~ ❯ rpg b
    potion[1]   200g
    remedy      400g
    escape      1000g

    funds: 797g
cmg in ❯ ~ ❯ rpg cd Downloads/
    wolf[1][xxxx]@~/Downloads
    wolf[1][xxxx] -30hp
    hero[3][xxxx] +10xp +59g
    hero[3][xxxx][xxx-]@~/Downloads
cmg in ❯ ~/Downloads ❯ rpg ls
cmg in ❯ ~/Downloads ❯ rpg cd Versions/
     rat[3][xxxx]@~/Downloads/Versions
    hero[3][xxxx] -2hp
     rat[3][xxxx] -33hp
    hero[3][xxxx] +33xp +38g
    hero[3][xxxx][xxxx]@~/Downloads/Versions
cmg in ❯ ~/Downloads/Versions ❯ rpg ls
📦   +405g
cmg in ❯ ~/Downloads/Versions ❯ rpg
    hero[3]@~/Downloads/Versions
    hp:[xxxxxxxxxx] 41/43
    xp:[xxxxxxxxx-] 125/155
    att:27   def:8   spd:13
    equip:{sword[1],shield[1]}
    item:{potionx7}
    894g
```

### PR DESCRIPTION
**Pull request by Silcet**
It should be working as intended now. I tested locally (took a while to find gold...) and it worked.

Maybe the new function for Game breaks your refactor. Please let me know if I can make it work better for you somehow :wink: 

Fixes #70

### CODE REVIEW

File: src/game/mod.rs [hunk 1]
```diff
@@ -141,6 +142,10 @@ impl Game {
         self.visit(Location::home()).unwrap_or_default();
     }
 
+    pub fn add_gold(&mut self, amount: i32) {
```
Comment (facundoolano) [inline src/game/mod.rs:145]: This function doesn't seem to add much, i'd rather just do `self.gold += amount;` directly (which is what's being done elsewhere to add gold). Also it doesn't need to be public.

Comment (Silcet) [reply src/game/mod.rs]: Followed suggestion :wink:

**Review by facundoolano — APPROVED** [review]

**Comment by facundoolano** [comment]
thanks!
